import { defineNuxtConfig } from "nuxt/config";

export default defineNuxtConfig({
  modules: ["@nuxt/ui", "@nuxtjs/i18n", "@nuxtjs/google-fonts"],
  pages: true,
  i18n: {
    locales: [
      { code: "en", iso: "en-US", file: "en.json" },
      { code: "es", iso: "es-ES", file: "es.json" },
      { code: "pt", iso: "pt-BR", file: "pt.json" },
    ],
    lazy: true,
    langDir: "i18n/locales",
    defaultLocale: "en",
  },
  googleFonts: {
    families: {
      Geist: [400, 500, 600, 700],
      Inter: [400, 500, 600],
    },
  },
  ui: {
    primary: 'afc6ff',
    gray: 'zinc',
    colors: [
      "on-error-container",
      "on-primary-container",
      "on-secondary-fixed-variant",
      "surface-container-lowest",
      "surface-container-high",
      "surface",
      "on-secondary-fixed",
      "on-tertiary-fixed-variant",
      "secondary-container",
      "on-tertiary-container",
      "on-surface",
      "on-surface-variant",
      "secondary",
      "secondary-fixed",
      "surface-container-highest",
      "success-vibrant",
      "on-secondary-container",
      "primary",
      "surface-container",
      "zinc-400",
      "surface-bright",
      "primary-container",
      "on-secondary",
      "on-primary-fixed-variant",
      "primary-fixed",
      "inverse-on-surface",
      "surface-dim",
      "error",
      "primary-fixed-dim",
      "outline-variant",
      "inverse-primary",
      "tertiary-container",
      "surface-container-low",
      "tertiary-fixed-dim",
      "background",
      "on-background",
      "on-primary-fixed",
      "zinc-800",
      "error-container",
      "on-tertiary-fixed",
      "warning-amber",
      "on-error",
      "tertiary-fixed",
      "outline",
      "slate-900",
      "tertiary",
      "surface-variant",
      "on-primary",
      "on-tertiary",
      "secondary-fixed-dim",
      "surface-tint",
      "inverse-surface",
    ],
  },
  devtools: { enabled: true },
});


